[project]
name = "skiing"
version = "0.0.1"
readme = "README.md"
authors = [{ name = "André Lima", email = "me@limwa.pt" }]
license-files = ["LICENSE"]
dependencies = [
  "pygame ~= 2.6"
]

[project.scripts]
play_skiing = "skiing.__main__:main"

[build-system]
requires = ["hatchling ~= 1.27"]
build-backend = "hatchling.build"
